function experiment = run_protocol_delay(proto_name,func_factory,is_sub7, ...
        q_range,lambda_val,sim_time_total_us,n_runs) %#ok<INUSD>
%RUN_PROTOCOL_DELAY Deprecated signature redirected to the v2 simulator.
% Existing user scripts keep working, but no legacy result is overwritten.
    if nargin<5 || isempty(lambda_val), lambda_val=5; end
    if nargin<6 || isempty(sim_time_total_us), sim_time_total_us=1e7; end
    if nargin<7 || isempty(n_runs), n_runs=1; end
    if nargin<4, q_range=[]; end

    names = struct( ...
        'sensing_free_connection_free','sf_cf', ...
        'sensing_free_connection_based','sf_cb', ...
        'sensing_based_connection_free','sb_cf', ...
        'sensing_based_connection_based','sb_cb', ...
        'sub_7G_assisted_clean','s7_clean', ...
        'sub_7G_assisted_busy','s7_busy');
    key = matlab.lang.makeValidName(char(proto_name));
    if ~isfield(names,key)
        error('run_protocol_delay:UnknownLegacyProtocol', ...
              'Cannot map legacy protocol name "%s" to v2.',proto_name);
    end
    warning('run_protocol_delay:RedirectedToV2', ...
        ['Legacy entry redirected to v2 (M=1:6, common 5-us arrivals, ', ...
         'versioned results_v2 output).']);
    experiment = run_protocol_compat_v2(names.(key),lambda_val, ...
        sim_time_total_us,n_runs,q_range);
end
