function report = run_sfcb_lightload_tests(output_dir)
%RUN_SFCB_LIGHTLOAD_TESTS Deterministic checks for isolated MAC variants.

    if nargin < 1 || isempty(output_dir)
        output_dir = fullfile(fileparts(mfilename('fullpath')), ...
            'results','verification');
    end
    if ~exist(output_dir,'dir'), mkdir(output_dir); end
    rows = struct('test',{},'passed',{},'detail',{});

    cfg = test_config(2,1);
    scenario = controlled_scenario(cfg);
    trace = make_manual_arrival_trace([0 50 300 450],[1 2 1 2],cfg);
    original = simulate_aloha_v2('sf_cb',trace,scenario,cfg,1,0.4,101);
    isolated = simulate_sfcb_lightload_variant( ...
        'baseline',trace,cfg,1,0.4,101);
    same = isequaln(original.packet_log.completion_us, ...
                    isolated.packet_log.completion_us) && ...
           isequaln(original.packet_log.hol_us, ...
                    isolated.packet_log.hol_us) && ...
           isequaln(original.packet_log.attempts, ...
                    isolated.packet_log.attempts);
    rows(end+1) = make_row('isolated_baseline_matches_original',same, ... %#ok<AGROW>
        'completion, HOL and attempt vectors must match exactly');

    cfg1 = test_config(1,1);
    scenario1 = controlled_scenario(cfg1);
    timing1 = mmw_timing_config(cfg1);
    trace1 = make_manual_arrival_trace(18,1,cfg1);
    fast = simulate_sfcb_lightload_variant( ...
        'fast_first',trace1,cfg1,1,1e-6,201);
    expected_slotted_attempt = timing1.CONN_SLOT_US;
    rows(end+1) = make_row('fast_first_ignores_normal_q_once', ... %#ok<AGROW>
        abs(fast.packet_log.first_attempt_us-expected_slotted_attempt)<1e-9, ...
        'empty-to-nonempty HOL must transmit at its first boundary');

    unslotted = simulate_sfcb_lightload_variant( ...
        'unslotted',trace1,cfg1,1,0.2,202,scenario1);
    expected_unslotted_completion = 18 + ...
        timing1.CONN_SLOT_US + timing1.CONN_SLOT_US;
    rows(end+1) = make_row('unslotted_has_no_boundary_wait', ... %#ok<AGROW>
        abs(unslotted.packet_log.first_attempt_us-18)<1e-9 && ...
        abs(unslotted.packet_log.completion_us- ...
            expected_unslotted_completion)<1e-9 && ...
        unslotted.diagnostics.rts_collision_window_us== ...
            timing1.RTS_US, ...
        'fresh HOL starts immediately and only the two-slot RTS is vulnerable');

    batch_trace = make_manual_arrival_trace([0 9 18],[1 1 1],cfg1);
    batch = simulate_sfcb_lightload_variant( ...
        'batch_clear',batch_trace,cfg1,1,1,301);
    conn = timing1.CONN_SLOT_US;
    expected_completion = [2*conn;3*conn;4*conn];
    expected_hol = [0;2*conn;3*conn];
    rows(end+1) = make_row('batch_clears_connection_snapshot', ... %#ok<AGROW>
        isequaln(batch.packet_log.completion_us,expected_completion) && ...
        isequaln(batch.packet_log.hol_us,expected_hol) && ...
        batch.diagnostics.max_batch_size==3, ...
        'three queued packets must use one reservation and sequential DATA');

    collision_trace = make_manual_arrival_trace([0 9],[1 2],cfg);
    collision = simulate_sfcb_lightload_variant( ...
        'unslotted',collision_trace,cfg,1,0.5,401,scenario);
    rows(end+1) = make_row('unslotted_rts_overlap_collides', ... %#ok<AGROW>
        collision.diagnostics.rts_fail_collision>=2 && ...
        collision.summary.packet_conservation_ok && ...
        all(isfinite(collision.packet_log.completion_us)), ...
        'only overlapping 18 us RTS frames must collide and later recover');

    nonoverlap_trace = make_manual_arrival_trace([0 18],[1 2],cfg);
    nonoverlap = simulate_sfcb_lightload_variant( ...
        'unslotted',nonoverlap_trace,cfg,1,0.5,402,scenario);
    rows(end+1) = make_row('unslotted_nonoverlap_is_not_rts_collision', ... %#ok<AGROW>
        nonoverlap.diagnostics.rts_fail_collision==0 && ...
        nonoverlap.diagnostics.rts_fail_ap_busy_start>=1 && ...
        all(isfinite(nonoverlap.packet_log.completion_us)), ...
        'an RTS starting after the first RTS ends is late, not an RTS collision');

    halfduplex_trace = make_manual_arrival_trace([0 36],[1 2],cfg);
    halfduplex = simulate_sfcb_lightload_variant( ...
        'unslotted',halfduplex_trace,cfg,1,0.5,403,scenario);
    rows(end+1) = make_row('unslotted_cts_halfduplex_and_phy_models', ... %#ok<AGROW>
        halfduplex.diagnostics.icr_miss_halfduplex>=1 && ...
        strcmp(halfduplex.diagnostics.cts_reception_model, ...
            'sector_scan_half_duplex_plus_sinr') && ...
        strcmp(halfduplex.diagnostics.data_reception_model, ...
            'directional_sinr'), ...
        'RTS transmission can miss sector CTS; CTS and DATA retain SINR models');

    stress_cfg = test_config(12,1);
    stress_cfg.measure_us = 2e6;
    stress_cfg.arrival_end_us = stress_cfg.measure_us;
    stress_cfg.sim_hard_end_us = stress_cfg.measure_us;
    stress_cfg = validate_experiment_config(stress_cfg);
    stress_trace = make_manual_arrival_trace(zeros(12,1),(1:12).', ...
        stress_cfg);
    stress_scenario = controlled_scenario(stress_cfg);
    stress = simulate_sfcb_lightload_variant( ...
        'unslotted',stress_trace,stress_cfg,2,0.01,601,stress_scenario);
    stress_done = isfinite(stress.packet_log.completion_us);
    component_error = stress.packet_log.access_delay_us - ( ...
        stress.packet_log.boundary_wait_us + ...
        stress.packet_log.difs_wait_us + ...
        stress.packet_log.probability_wait_us + ...
        stress.packet_log.busy_nav_wait_us + ...
        stress.packet_log.collision_delay_us + ...
        stress.packet_log.control_delay_us + ...
        stress.packet_log.data_delay_us + ...
        stress.packet_log.other_access_delay_us);
    rows(end+1) = make_row('unslotted_long_retry_component_identity', ... %#ok<AGROW>
        all(stress_done) && all(abs(component_error(stress_done))<1e-9), ...
        'long collision/retry histories must retain exact delay accounting');

    variants = {'baseline','fast_first','unslotted','batch_clear'};
    identities_ok = true;
    for i = 1:numel(variants)
        result = simulate_sfcb_lightload_variant( ...
            variants{i},batch_trace,cfg1,1,0.5,500+i,scenario1);
        done = isfinite(result.packet_log.completion_us);
        error_us = result.packet_log.total_delay_us(done) - ...
            result.packet_log.queue_delay_us(done) - ...
            result.packet_log.access_delay_us(done);
        identities_ok = identities_ok && all(abs(error_us)<1e-9) && ...
            result.summary.packet_conservation_ok;
    end
    rows(end+1) = make_row('all_variants_delay_identity', ... %#ok<AGROW>
        identities_ok,'total delay must equal queue plus access delay');

    report = struct2table(rows);
    writetable(report,fullfile(output_dir,'tests.csv'));
    save(fullfile(output_dir,'tests.mat'),'report');
    if ~all(report.passed)
        failed = strjoin(cellstr(string(report.test(~report.passed))),', ');
        error('run_sfcb_lightload_tests:Failure', ...
            'Failed tests: %s',failed);
    end
    fprintf('SF-CB light-load tests passed: %d/%d\n', ...
        height(report),height(report));
end

function scenario = controlled_scenario(cfg)
    scenario = prepare_scenario_v2(cfg,cfg.topology_seed);
    n = cfg.n_nodes;
    scenario.PHY.Int_Matrix = zeros(n,n);
    scenario.PHY.AP_Rx_Matrix = eye(n)*1e-6;
    scenario.PHY.AP_Sector_Tx_Matrix = ones(n,cfg.n_sectors)*1e-6;
end

function cfg = test_config(n_nodes,n_sectors)
    cfg = default_lightload_sfcb_config('smoke');
    cfg.n_nodes = n_nodes;
    cfg.n_sectors = n_sectors;
    cfg.protocols = {'sf_cb'};
    cfg.robustness_protocols = {'sf_cb'};
    cfg.warmup_us = 0;
    cfg.measure_us = 1e4;
    cfg.drain_max_us = 4e4;
    cfg.arrival_end_us = cfg.measure_us;
    cfg.sim_hard_end_us = cfg.arrival_end_us + cfg.drain_max_us;
    cfg.stats_sample_us = 9;
    cfg.stability_rate_tolerance = 1;
    cfg.stability_censor_tolerance = 1;
    cfg.stability_require_slope = false;
    cfg = validate_experiment_config(cfg);
end

function row = make_row(name,passed,detail)
    row = struct('test',string(name),'passed',logical(passed), ...
        'detail',string(detail));
end
