workspace_root = fileparts(fileparts(mfilename('fullpath')));
root_dir = fullfile(workspace_root, 'results_v2', ...
    '20260723_200440_dae2255a7e44', 'combined_view');
summary = readtable(fullfile(root_dir, 'summary.csv'), ...
    'TextType', 'string', 'VariableNamingRule', 'preserve');
unstable = summary(summary.stable_fraction < 1, :);

rows = table();
for c = 1:height(unstable)
    protocol = string(unstable.protocol(c));
    load_mode = string(unstable.load_mode(c));
    lambda_base = unstable.lambda_base(c);
    M = unstable.M(c);
    stem = sprintf('%s_%s_lam%g_M%g.mat', ...
        protocol, load_mode, lambda_base, M);
    loaded = load(fullfile(root_dir, 'checkpoints', stem));
    tuning = loaded.condition.tuning;
    grid = tuning.grid;
    for g = 1:numel(grid)
        run_summaries = grid(g).run_summaries;
        mean_arrival = mean([run_summaries.arrival_rate_pkt_s]);
        mean_goodput = mean([run_summaries.goodput_pkt_s]);
        mean_completion = mean([run_summaries.completion_ratio]);
        mean_slope = mean([run_summaries.backlog_slope_pkt_s]);
        mean_final_backlog = mean([run_summaries.final_backlog]);
        row = table(protocol, load_mode, lambda_base, M, ...
            tuning.best_q, grid(g).q, grid(g).stable_fraction, ...
            grid(g).mean_delay_us, grid(g).mean_p95_us, ...
            grid(g).mean_collision_waste_us, ...
            grid(g).rate_screen_rejected_fraction, ...
            mean_arrival, mean_goodput, mean_completion, ...
            mean_slope, mean_final_backlog, ...
            'VariableNames', {'protocol','load_mode','lambda_base','M', ...
            'best_q','q','tuning_stable_fraction','mean_delay_us', ...
            'mean_p95_us','mean_collision_waste_us', ...
            'rate_screen_rejected_fraction','mean_arrival_rate_pkt_s', ...
            'mean_goodput_pkt_s','mean_completion_ratio', ...
            'mean_backlog_slope_pkt_s','mean_final_backlog'});
        rows = [rows; row]; %#ok<AGROW>
    end
end

writetable(unstable, fullfile(workspace_root, '.codex-tmp', ...
    'unstable_summary.csv'));
writetable(rows, fullfile(workspace_root, '.codex-tmp', ...
    'unstable_q_grid.csv'));
fprintf('unstable_conditions=%d q_grid_rows=%d\n', ...
    height(unstable), height(rows));
