project_dir = fileparts(fileparts(mfilename('fullpath')));
root_dir = fullfile(project_dir,'results_v2','20260726_191557_a6ccf7195cee','combined_view');
summary = readtable(fullfile(root_dir,'summary.csv'),'VariableNamingRule','preserve');
selected = summary(summary.M == 1 ...
    & ismember(string(summary.protocol),["sb_cf","sf_cb"]),:);

tuning_rows = table();
evaluation_rows = table();
for i = 1:height(selected)
    protocol = string(selected.protocol(i));
    load_mode = string(selected.load_mode(i));
    lambda_base = double(selected.lambda_base(i));
    tag = sprintf('%s_%s_lam%g_M1',protocol,load_mode,lambda_base);
    checkpoint_path = fullfile(root_dir,'checkpoints',[tag '.mat']);
    data = load(checkpoint_path);
    condition = data.condition;

    grid = condition.tuning.grid;
    for gi = 1:numel(grid)
        row = table(protocol,load_mode,lambda_base,double(grid(gi).q), ...
            double(grid(gi).stable_fraction),double(grid(gi).mean_delay_us), ...
            double(grid(gi).mean_p95_us),double(grid(gi).mean_collision_waste_us), ...
            'VariableNames',{'protocol','load_mode','lambda_base','q', ...
            'tune_stable_fraction','tune_mean_delay_us','tune_mean_p95_us', ...
            'tune_mean_collision_waste_us'});
        tuning_rows = [tuning_rows; row]; %#ok<AGROW>
    end

    evals = condition.evaluation;
    for ri = 1:numel(evals)
        s = evals{ri}.summary;
        row = table(protocol,load_mode,lambda_base,double(condition.tuning.best_q),ri, ...
            logical(s.stable),double(s.mean_delay_us),double(s.mean_queue_delay_us), ...
            double(s.mean_access_delay_us),double(s.mean_boundary_wait_us), ...
            double(s.mean_difs_wait_us),double(s.mean_probability_wait_us), ...
            double(s.mean_busy_nav_wait_us),double(s.mean_collision_delay_us), ...
            double(s.mean_control_delay_us),double(s.mean_data_delay_us), ...
            double(s.mean_attempts_completed),double(s.arrival_rate_pkt_s), ...
            double(s.goodput_pkt_s),double(s.final_backlog), ...
            double(s.backlog_slope_pkt_s),double(s.little_relative_error), ...
            'VariableNames',{'protocol','load_mode','lambda_base','selected_q','run', ...
            'stable','mean_delay_us','queue_delay_us','access_delay_us', ...
            'boundary_wait_us','difs_wait_us','probability_wait_us','busy_nav_wait_us', ...
            'collision_delay_us','control_delay_us','data_delay_us','mean_attempts', ...
            'arrival_rate','goodput_rate','final_backlog','backlog_slope', ...
            'little_relative_error'});
        evaluation_rows = [evaluation_rows; row]; %#ok<AGROW>
    end
end

out_dir = fullfile(project_dir,'.codex-tmp');
writetable(tuning_rows,fullfile(out_dir,'m1_sb_cf_sf_cb_tuning.csv'));
writetable(evaluation_rows,fullfile(out_dir,'m1_sb_cf_sf_cb_evaluation.csv'));
disp(selected(:,{'protocol','load_mode','lambda_base','best_q','stable_fraction', ...
    'mean_delay_us','mean_queue_delay_us','mean_access_delay_us'}));
