cfg1 = default_saturation_config('smoke');
cfg1.n_nodes = 1;
cfg1.n_sectors = 1;
cfg1.warmup_us = 0;
timing1 = mmw_timing_config(cfg1);
conn1_us = timing1.CONN_SLOT_US;
cfg1.measure_us = conn1_us*120;
cfg1.arrival_end_us = cfg1.measure_us;
cfg1.sim_hard_end_us = cfg1.measure_us;
cfg1.run_preflight_tests = false;
cfg1.parallel = false;
cfg1 = validate_saturation_config(cfg1);
scenario1 = prepare_scenario_v2(cfg1,cfg1.topology_seed);
cfg_cb = cfg1;
cfg_cb.measure_us = (conn1_us+2*conn1_us)*100;
cfg_cb.arrival_end_us = cfg_cb.measure_us;
cfg_cb.sim_hard_end_us = cfg_cb.measure_us;
trace_cb = make_saturation_trace(cfg_cb);
sf_cb = run_protocol_v2('sf_cb',trace_cb,scenario1,cfg_cb,2,1,102);
fprintf('airtime=%.6f (expect 0.6667) Tp=%.1f\n', sf_cb.summary.payload_airtime_fraction, sf_cb.summary.Tp_us);
fprintf('completed=%.0f pkt_s=%.4f effM=%.3f\n', sf_cb.summary.completed_packets, sf_cb.summary.completed_pkt_s, ...
    sf_cb.summary.effective_M);
