cfg1 = default_saturation_config('smoke');
cfg1.n_nodes = 1;
cfg1.n_sectors = 1;
cfg1.warmup_us = 0;
timing1 = mmw_timing_config(cfg1);
real_conn1_us = cfg1.mmw_real_conn_slot_us;
cfg1.measure_us = real_conn1_us*120;
cfg1.arrival_end_us = cfg1.measure_us;
cfg1.sim_hard_end_us = cfg1.measure_us;
cfg1.run_preflight_tests = false;
cfg1.parallel = false;
cfg1 = validate_saturation_config(cfg1);
scenario1 = prepare_scenario_v2(cfg1,cfg1.topology_seed);
trace1 = make_saturation_trace(cfg1);
sf_cf = run_protocol_v2('sf_cf',trace1,scenario1,cfg1,1,1,101);
fprintf('sf_cf airtime=%.6f (expect 1.0) Tp=%.1f\n', sf_cf.summary.payload_airtime_fraction, sf_cf.summary.Tp_us);
fprintf('completed=%d pkt_s=%.4f\n', sf_cf.summary.completed_packets, sf_cf.summary.completed_pkt_s);
