cfg = default_experiment_config('smoke');
cfg.n_nodes = 8;
cfg.cca_mode = 'disabled';
cfg.collect_debug_trace = true;
cfg.warmup_us = 0; cfg.measure_us = 300; cfg.drain_max_us = 0;
cfg.arrival_end_us = 300; cfg.sim_hard_end_us = 300;
scenario = prepare_scenario_v2(cfg, 44);
trace = make_manual_arrival_trace([0;0],[1;2],cfg);
r = simulate_sb_cb_v2(trace,scenario,cfg,1,1,171);
fprintf('collision_delay: %s\n', mat2str(r.packet_log.collision_delay_us));
fprintf('rts_start: %s\n', mat2str(r.diagnostics.rts_start_times_us));
fprintf('node2_starts: %s\n', mat2str(r.diagnostics.rts_start_times_us(r.diagnostics.rts_start_nodes==2)));
cfg2 = default_experiment_config('smoke');
cfg2.n_nodes = 40; cfg2.cca_mode='directional'; cfg2.collect_debug_trace=true;
cfg2.warmup_us=0; cfg2.measure_us=700; cfg2.drain_max_us=700;
cfg2.arrival_end_us=700; cfg2.sim_hard_end_us=1400;
sc2 = prepare_scenario_v2(cfg2, 482);
sc2.PHY.Int_Matrix(:)=0; sc2.PHY.AP_Sector_Tx_Matrix(:)=1e-6; sc2.PHY.AP_Rx_Matrix(:)=0;
sc2.PHY.AP_Rx_Matrix(1:cfg2.n_nodes+1:end)=1e-6;
tr2 = make_manual_arrival_trace([0;99],[1;3],cfg2);
r2 = simulate_sb_cb_v2(tr2,sc2,cfg2,1,1,483);
fprintf('nav_set=%d\n', r2.diagnostics.nav_set);
fprintf('node3_starts: %s\n', mat2str(r2.diagnostics.rts_start_times_us(r2.diagnostics.rts_start_nodes==3)));
